const fs = require('fs');
const path = require('path');

// Paths for input JSON and output Netscape cookies
const jsonCookiesPath = path.join(__dirname, 'cookies.json');
const netscapeCookiesPath = path.join(__dirname, 'cookies.txt');

// Function to convert JSON cookies to Netscape format
function convertJsonToNetscape(jsonCookies) {
  // Header for Netscape cookies.txt file
  let netscapeCookies =
    '# Netscape HTTP Cookie File\n# https://curl.haxx.se/rfc/cookie_spec.html\n# This file was generated by yt-dlp converter\n\n';

  // Process each cookie
  for (const cookie of jsonCookies) {
    // Skip cookies without necessary fields
    if (!cookie.domain || !cookie.name || !cookie.value) continue;

    // Format: domain flag path secure expiry name value
    const domain = cookie.domain.startsWith('.')
      ? cookie.domain
      : cookie.domain;
    const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expirationDate
      ? Math.floor(cookie.expirationDate)
      : 0;

    // Append cookie line in Netscape format
    netscapeCookies += `${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}\n`;
  }

  return netscapeCookies;
}

try {
  // Read the JSON cookies file
  const jsonData = fs.readFileSync(jsonCookiesPath, 'utf8');
  const jsonCookies = JSON.parse(jsonData);

  // Convert to Netscape format
  const netscapeCookies = convertJsonToNetscape(jsonCookies);

  // Write to Netscape cookies.txt file
  fs.writeFileSync(netscapeCookiesPath, netscapeCookies);

  console.log('Cookies successfully converted to Netscape format!');
  console.log(`Output saved to: ${netscapeCookiesPath}`);
} catch (err) {
  console.error('Error converting cookies:', err);
}
